### PR TITLE
Feature/support hide visibility from staff

### PR DESCRIPTION
**Pull request by hafsabatool7**
http://pm.7vals.com/issues/12936 (Redmine Ticket)
https://github.com/7Vals/ezofficeinventory/pull/11675 (Associated PR)

### CODE REVIEW

**Comment by hafsabatool7** [comment]
Cycle-0

**Comment by Anmol79** [comment]
Cycle-1

**Comment by saqibbukhari** [comment]
pull latest code

**Comment by hafsabatool7** [comment]
Comments resolved

**Pull request merged**
